### ISSUE TITLE
feat: Nyancatのプログレスバー( またはどっかに走らせとく)みたいなのほしいな

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [Potato1682/nvim#11]

**Comment by Potato1682** [comment]
Neovim / vimはそもそもプログレスバーが必要ないレベルで高速に動作します。
LSPの起動時間も数秒かかるだけで、すぐにコード補完が提供される仕組みになっています。
それでもほしいのなら検討しますが、どうでしょう？

**Comment by PeyaPeyaPeyang** [comment]
slみたいな感覚ですみにはしらせたいな

**Comment by Potato1682** [comment]
そもそもプログレスバーが必要になる場面がよくわかりません。
slみたいな感覚とはどのような感じでしょうか。

**Comment by PeyaPeyaPeyang** [comment]
画面のあまってるとこにNyancatずっと常駐させるやつ

**Comment by Potato1682** [comment]
Galaxylineがアニメーションに対応しているかによって異なるかもしれません。
Galaxylineにインターバルでセグメントを表示できるなら普通に自前で実装できるかもしないですね。
それでは、**文字**で**一行のみ**で**ステータスバーの半分以上を独占しない**キーフレームをください。

**Comment by PeyaPeyaPeyang** [comment]
気合

**Comment by Potato1682** [comment]
そうなのであればクローズしますね。
気合で自前設定してください。
