### ISSUE TITLE
feat: LICENSE 自動生成してほしいな

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [Potato1682/nvim#12]
MIT, GPLv2 etc...  
著作者自分で設定しておいたやつを読むようにしたいな

**Comment by Potato1682** [comment]
そのようなプラグインが多数見つかったので、検討しておきます。

**Comment by PeyaPeyaPeyang** [comment]
定義ファイル自作できるようにしたいな

**Comment by Potato1682** [comment]
別にライセンスくらいまとめてる[機関](https://opensource.org)があるのであんまり必要性はないと思います。

**Comment by PeyaPeyaPeyang** [comment]
それプロジェクトつくるごとに行くのめんどくさいんで

**Comment by PeyaPeyaPeyang** [comment]
![image](https://user-images.githubusercontent.com/42040068/120103652-a6eb8580-c18b-11eb-97d5-6cc532adbf19.png)

**Comment by Potato1682** [comment]
コメント見てますか？生成するプラグインがあると私はすでにコメントしています。

**Comment by Potato1682** [comment]
現在のエディター上にライセンスを突っ込んでくれる[プラグイン](https://github.com/antoyo/vim-licenses)が見つかったので、これを使用します。
コマンドを使用するため、使いたいライセンスのコマンドを先に覚えておくと便利でしょう。
エディター上にライセンスを設置するため、LICENSEを新しく作って編集しているときにコマンドを叩くとLICENSEがうまくできます。
