### ISSUE TITLE
feat: Redmineと連携したいな

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [Potato1682/nvim#16]

**Comment by Potato1682** [comment]
そのようなプラグインが見つかったので検討しておきます。

**Comment by Potato1682** [comment]
実装しました。
RedmineでRESTサポートを有効にし、
[nvim-settings](https://github.com/Potato1682/nvim/blob/nvim-settings.lua)の
- `redmine.site`
- `redmine.api_key`

を設定してください。
プラグインで実装されているコマンドを見たい場合は[こちら](https://github.com/toritori0318/vim-redmine)を参照してみてください。
コマンドが面倒な場合はキーマッピングができるので、ほしければキーの組み合わせと一緒にコメントしてください。
