### ISSUE TITLE
feat: important: クラス移動するとき package 句も変わってほしいな (リファクタリング)

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [Potato1682/nvim#17]

**Comment by Potato1682** [comment]
LSPによってそのサポートレベルは異なりますが、TypeScript LSPにはシンボルのリネームが存在するようです。
なんの言語に対してのLSPかまったく書いていないようですが、LSPによって異なることに留意してください。

**Comment by PeyaPeyaPeyang** [comment]
Javaだけでもたいおうしてほしいな

**Comment by Potato1682** [comment]
**LSPのクライアント**の設定に対してそれを要求するのはどうなんですか？
そんなに対応してほしいのでしたらjdt-lsでIssueを立ててください。
