### ISSUE TITLE
feat: ブレークポイントおいてデバッグしたいな (リモート、ろーかる、VMアタッチ etc...)

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [Potato1682/nvim#18]

**Comment by Potato1682** [comment]
[Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol)に従って実装されたプラグインの[nvim-dap](https://github.com/mfussenegger/nvim-dap)はすでにインストールされており、対応しています。

**Comment by PeyaPeyaPeyang** [comment]
Javaでもうごく？

**Comment by Potato1682** [comment]
DAPに対応していればアタッチすることにより対応できます。

**Comment by Potato1682** [comment]
たまたま目に入ったので報告しますが、jdt-lsはDAPをサポートしているようです。
そのため、普通にJavaでデバッグはできるようになっています。
