### ISSUE TITLE
feat: Markdownレンダリングしたいな

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [Potato1682/nvim#19]

**Comment by Potato1682** [comment]
そのようなプラグインが見つかったので、検討しておきます。

**Comment by PeyaPeyaPeyang** [comment]
GitHubの書き方ほしいな

<>, style, etc...

**Comment by Potato1682** [comment]
なんのプラグインを使用するかまだ決めていないので、それらに対しては追ってコメントします。

**Comment by Potato1682** [comment]
[このプラグイン](https://github.com/iamcco/markdown-preview.nvim)を使用しました。
`Space` -> `m`キーで切り替えできます。
