### ISSUE TITLE
feat: パッケージまとめたいな

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [Potato1682/nvim#23]

**Comment by Potato1682** [comment]
どういうことですか？

**Comment by PeyaPeyaPeyang** [comment]
ファイル一覧のとこのパッケージ
```
a
|- b
 |- c
     |-hoge.JAVA
```
を
```
a.b.c
      |-hoge.JAVA

**Comment by Potato1682** [comment]
一回nvim-treeがまとめてくれていた...気がする。
ちょっと確認してみます。

**Comment by Potato1682** [comment]
それっぽいオプション (`vim.g.nvim_tree_group_empty`)は見つけたんですが、うまく動いてくれていないようですね。
ひとまずサポートしていないこととしクローズします。

**Comment by Potato1682** [comment]
サポートが確認されました。
89bf6d1 より使用可能です。
![image](https://user-images.githubusercontent.com/48394190/120109287-b4ad0500-c1a3-11eb-954b-2eb4dee9dd63.png)
