### ISSUE TITLE
feat: いろいろ自動生成したいな

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [Potato1682/nvim#24]
![image](https://user-images.githubusercontent.com/42040068/120104009-5412cd80-c18d-11eb-8239-b270811722b6.png)

**Comment by Potato1682** [comment]
テンプレートを生成するプラグインは一応[ある](https://github.com/thinca/vim-template)んですが、テンプレートを書くときに少々手こずるかもしれません。

**Comment by Potato1682** [comment]
夜ふかしを続け悪戦苦闘の末テンプレートファイルを無事作成できました。
エクスプローラーや:eコマンドでJavaファイルを作るときに
- `*.java` - クラス
- `A*.java` - アノテーション
- `E*.java` - 列挙型
- `I*.java` - インターフェース

という感じで生成されます。
カーソルはブランケット内に移動してくれます。

**Comment by Potato1682** [comment]
テンプレートファイルを自前で追加する場合は、以下の文字列が使用できます。
- `<+CLASS NAME+>`: 拡張子抜きのファイル名。
- `<+CURSOR+>`: カーソル位置。
- `:command`: コマンド実行。ファイル先頭に書いてください。複数のコマンドを並べて実行できます。

変にenterで開けたりするとそれも認識されることがあります。
Javaのパッケージ取得の際にコマンドを使用していますので、`<+PACKAGE+>`で置き換えしたい場合には[こちら](https://github.com/Potato1682/nvim/blob/main/template/Itemplate.java)からコピーしてパターンを書き換えると良いかもしれません。
