### ISSUE TITLE
feat: GitHub workflow対応してほしいな

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [Potato1682/nvim#29]

**Comment by Potato1682** [comment]
GitHub workflowに対応してどういうことをしたいのですか？
機能の詳細を説明してください。

**Comment by PeyaPeyaPeyang** [comment]
その項にあった候補を出してほしいな

**Comment by Potato1682** [comment]
もう少し詳しく説明してください。

**Comment by PeyaPeyaPeyang** [comment]
on: 
までいれたら push とか issue とかでてくるやつ

**Comment by Potato1682** [comment]
たぶん...ないです。
YAMLにたいするLSPサーバーは実装済みなので、YAML構文エラーのチェックはしてくれますが、それで足しになれば。
