### ISSUE TITLE
feat: タイポ指摘してくれるやつほしいな

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [Potato1682/nvim#30]

**Comment by Potato1682** [comment]
そのようなものが結構あったので、検討しておきます。

**Comment by Potato1682** [comment]
cspellをdiagnosticlsでラップしてみるとかneovimのスペルチェッカーを使ってみるとかいろいろ試したんですが、有能なスペルチェッカーがいませんでした。
そのため、サポートは難しいとしクローズします。

**Comment by Potato1682** [comment]
あ っ た
