### ISSUE TITLE
feat: Easy diff plugin

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [Potato1682/nvim#37]

**Comment by PeyaPeyaPeyang** [comment]
![image](https://user-images.githubusercontent.com/42040068/120297303-efc64a00-c303-11eb-96b2-b0af5eced50f.png)

**Comment by Potato1682** [comment]
これはあくまで推測であり憶測混じりの主観が入るかｍ(ry
たぶんないです、ごめんなさい...

**Comment by Potato1682** [comment]
それっぽいdiffプラグインは見つけたので、導入を検討してみます。
