### ISSUE TITLE
feat: カラースキームを自作できるコンフィグ

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [Potato1682/nvim#65]

**Comment by Potato1682** [comment]
`colors/` ディレクトリ直下にluaまたはvimファイルを作成することで独自のカラースキームを運用することができます。
しかしながら、nvimは`edge`カラースキームを尊重した状態で開発しているため、新たなカラースキームの定義はあまりおすすめできません。
最も手っ取り早い方法は、[`events.on_color()`](https://github.com/Potato1682/nvim/blob/fac17a852296561137412da189387b11317c6ea4/lua/events.lua#L92-L105)の末尾に独自のハイライト設定を書いていくことです。
