### ISSUE TITLE
feat: Mavenの依存関係いい感じに読んでほしいな。

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [Potato1682/nvim#7]

**Comment by Potato1682** [comment]
依存関係アシスタントというシステムを作った人は[一応いる](https://github.com/akinsho/dependency-assist.nvim)んですが、Mavenに対しては実装を予定していなかったようです。
なにか発見があれば追ってコメントします。

**Comment by Potato1682** [comment]
結構探しましたがなかったのでクローズします。
