### ISSUE TITLE
feat: ハイライト色じぶんで調整できるスクリーンみたいのほしいな

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [Potato1682/nvim#9]

**Comment by Potato1682** [comment]
そのようなものは存在しませんが、Luaでのカラースキームの編集時に自動でカラースキームをリアルタイム適用してくれる[colorbuddy.nvim](https://github.com/tjdevries/colorbuddy.nvim)が存在するので導入を検討してみます。
ただし、colorbuddy.nvimはLuaでカラースキームを編集するため、ある程度Lua記法とcolorbuddyの書き方を理解しておく必要があります。
